language: node_js
node_js:
  - "stable"
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  local_dir: public
  target_branch: gh-pages
  on:
    branch: master
before_script:
  - "npm i -g gatsby"
  - "npm i"
script:
  - "npm run test"
  - "gatsby build --prefix-paths"
after_success:
  - "gh-pages -d public"
